version: '3'
services:

  ## ------------ Sample database -----------------------
  pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    volumes:
      - pgsql-data:/tmp/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./insert.sql:/docker-entrypoint-initdb.d/insert.sql
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    depends_on: 
      - pgsql
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: postgres
    ports:
      - 8081:8080
  ## ------------ Sample database -----------------------

volumes:
  pgsql-data:

networks: 
  default: 
    external: 
      name: my-network

